/* eslint-disable no-undef */
export const usePosition = () => {
  const { t, tm, rt } = useI18n()
  const jobPosition = [
    {
      id: 'assistant-chief-executive-officer',
      title: t('position[0].title'),
      qualification: tm('position[0].qualification'),
      responsibility: tm('position[0].responsibility'),
      type: t('career.assistant'),
      location: t('position[0].location'),
      time: t('position[0].time'),
      skill: t('position[0].skill'),
    },
    {
      id: 'business-development-engineer',
      title: t('position[1].title'),
      qualification: tm('position[1].qualification'),
      responsibility: tm('position[1].responsibility'),
      type: t('career.marketing'),
      location: t('position[1].location'),
      time: t('position[1].time'),
      skill: t('position[1].skill'),
    },
    {
      id: 'crack-detection-analysis-and-reporting-specialist',
      title: t('position[2].title'),
      qualification: tm('position[2].qualification'),
      responsibility: tm('position[2].responsibility'),
      type: t('career.engineer'),
      location: t('position[2].location'),
      time: t('position[2].time'),
      skill: t('position[2].skill'),
    },
    {
      id: 'data-analysis-and-reporting-officer',
      title: t('position[3].title'),
      qualification: tm('position[3].qualification'),
      responsibility: tm('position[3].responsibility'),
      type: t('career.engineer'),
      location: t('position[3].location'),
      time: t('position[3].time'),
      skill: t('position[3].skill'),
    },
    {
      id: 'dtc-sales-manager',
      title: t('position[4].title'),
      qualification: tm('position[4].qualification'),
      responsibility: tm('position[4].responsibility'),
      type: t('career.sales'),
      location: t('position[4].location'),
      time: t('position[4].time'),
      skill: t('position[4].skill'),
    },
    {
      id: 'electronics-specialist',
      title: t('position[5].title'),
      qualification: tm('position[5].qualification'),
      responsibility: tm('position[5].responsibility'),
      type: t('career.electronics'),
      location: t('position[5].location'),
      time: t('position[5].time'),
      skill: t('position[5].skill'),
    },
    {
      id: 'fpfga-engineer',
      title: t('position[6].title'),
      qualification: tm('position[6].qualification'),
      responsibility: tm('position[6].responsibility'),
      type: t('career.electronics'),
      location: t('position[6].location'),
      time: t('position[6].time'),
      skill: t('position[6].skill'),
    },
    {
      id: 'general-manager',
      title: t('position[7].title'),
      qualification: tm('position[7].qualification'),
      responsibility: tm('position[7].responsibility'),
      type: t('career.business'),
      location: t('position[7].location'),
      time: t('position[7].time'),
      skill: t('position[7].skill'),
    },
    {
      id: 'international-sales-and-business-development-specialist',
      title: t('position[8].title'),
      qualification: tm('position[8].qualification'),
      type: t('career.marketing'),
      location: t('position[8].location'),
      time: t('position[8].time'),
      skill: t('position[8].skill'),
    },
    {
      id: 'programmer',
      title: t('position[9].title'),
      qualification: tm('position[9].qualification'),
      type: t('career.programmer'),
      location: t('position[9].location'),
      time: t('position[9].time'),
      skill: t('position[9].skill'),
    },
    {
      id: 'sales-engineer',
      title: t('position[10].title'),
      qualification: tm('position[10].qualification'),
      responsibility: tm('position[10].responsibility'),
      type: t('career.sales'),
      location: t('position[10].location'),
      time: t('position[10].time'),
      skill: t('position[10].skill'),
    },
    {
      id: 'sap-business-one-specialist',
      title: t('position[11].title'),
      qualification: tm('position[11].qualification'),
      type: t('career.business'),
      location: t('position[11].location'),
      time: t('position[11].time'),
      skill: t('position[11].skill'),
    },
    {
      id: 'simulation-engineer',
      title: t('position[12].title'),
      qualification: tm('position[12].qualification'),
      responsibility: tm('position[12].responsibility'),
      type: t('career.engineer'),
      location: t('position[12].location'),
      time: t('position[12].time'),
      skill: t('position[12].skill'),
    },
    {
      id: 'software-engineer',
      title: t('position[13].title'),
      qualification: tm('position[13].qualification'),
      responsibility: tm('position[13].responsibility'),
      type: t('career.engineer'),
      location: t('position[13].location'),
      time: t('position[13].time'),
      skill: t('position[13].skill'),
    },
    {
      id: 'sr-ili-engineer',
      title: t('position[14].title'),
      qualification: tm('position[14].qualification'),
      responsibility: tm('position[14].responsibility'),
      type: t('career.engineer'),
      location: t('position[14].location'),
      time: t('position[14].time'),
      skill: t('position[14].skill'),
    },
    {
      id: 'test-engineer',
      title: t('position[15].title'),
      qualification: tm('position[15].qualification'),
      responsibility: tm('position[15].responsibility'),
      type: t('career.engineer'),
      location: t('position[15].location'),
      time: t('position[15].time'),
      skill: t('position[15].skill'),
    },
    {
      id: 'transducer-technician',
      title: t('position[16].title'),
      qualification: tm('position[16].qualification'),
      responsibility: tm('position[16].responsibility'),
      other_responsibility: tm('position[16].other_responsibility'),
      type: t('career.electronics'),
      location: t('position[16].location'),
      time: t('position[16].time'),
      skill: t('position[16].skill'),
    },
    {
      id: 'cash-management-specialist',
      title: t('position[17].title'),
      qualification: tm('position[17].qualification'),
      responsibility: tm('position[17].responsibility'),
      other_responsibility: tm('position[17].other_responsibility'),
      type: t('career.accounting'),
      location: t('position[17].location'),
      time: t('position[17].time'),
      skill: t('position[17].skill'),
    },
    {
      id: 'machining-operator',
      title: t('position[18].title'),
      qualification: tm('position[18].qualification'),
      responsibility: tm('position[18].responsibility'),
      other_responsibility: tm('position[18].other_responsibility'),
      type: t('career.programmer'),
      location: t('position[18].location'),
      time: t('position[18].time'),
      skill: t('position[18].skill'),
    },
    {
      id: 'connector-technician',
      title: t('position[19].title'),
      qualification: tm('position[19].qualification'),
      responsibility: tm('position[19].responsibility'),
      other_responsibility: tm('position[19].other_responsibility'),
      type: t('career.electronics'),
      location: t('position[19].location'),
      time: t('position[19].time'),
      skill: t('position[19].skill'),
    },
    {
      id: 'assembly-technician',
      title: t('position[20].title'),
      qualification: tm('position[20].qualification'),
      responsibility: tm('position[20].responsibility'),
      other_responsibility: tm('position[20].other_responsibility'),
      type: t('career.programmer'),
      location: t('position[20].location'),
      time: t('position[20].time'),
      skill: t('position[20].skill'),
    },
    {
      id: 'financial-capital-market-and-investor-relation-specialist',
      title: t('position[21].title'),
      qualification: tm('position[21].qualification'),
      responsibility: tm('position[21].responsibility'),
      type: t('career.business'),
      location: t('position[21].location'),
      time: t('position[21].time'),
      skill: t('position[21].skill'),
    },
    {
      id: 'international-sales-support',
      title: t('position[22].title'),
      qualification: tm('position[22].qualification'),
      responsibility: tm('position[22].responsibility'),
      type: t('career.marketing'),
      location: t('position[22].location'),
      time: t('position[22].time'),
      skill: t('position[22].skill'),
    },
    {
      id: 'quality-safety-management-system-department-manager',
      title: t('position[23].title'),
      qualification: tm('position[23].qualification'),
      responsibility: tm('position[23].responsibility'),
      other_responsibility: tm('position[23].other_responsibility'),
      type: t('career.engineer'),
      location: t('position[23].location'),
      time: t('position[23].time'),
      skill: t('position[23].skill'),
    },
    {
      id: 'transducer-engineer',
      title: t('position[24].title'),
      qualification: tm('position[24].qualification'),
      responsibility: tm('position[24].responsibility'),
      other_responsibility: tm('position[24].other_responsibility'),
      type: t('career.electronics'),
      location: t('position[24].location'),
      time: t('position[24].time'),
      skill: t('position[24].skill'),
    },
    {
      id: 'marketing-manager',
      title: t('position[25].title'),
      qualification: tm('position[25].qualification'),
      responsibility: tm('position[25].responsibility'),
      type: t('career.marketing'),
      location: t('position[25].location'),
      time: t('position[25].time'),
      skill: t('position[25].skill'),
    },
    {
      id: 'automation-engineer',
      title: t('position[26].title'),
      qualification: tm('position[26].qualification'),
      responsibility: tm('position[26].responsibility'),
      other_responsibility: tm('position[26].other_responsibility'),
      type: t('career.programmer'),
      location: t('position[26].location'),
      time: t('position[26].time'),
      skill: t('position[26].skill'),
    },
    {
      id: 'ms-power-platform-engineer',
      title: t('position[27].title'),
      qualification: tm('position[27].qualification'),
      responsibility: tm('position[27].responsibility'),
      type: t('career.programmer'),
      location: t('position[27].location'),
      time: t('position[27].time'),
      skill: t('position[27].skill'),
    },
    {
      id: 'public-relation-specialist',
      title: t('position[28].title'),
      qualification: tm('position[28].qualification'),
      responsibility: tm('position[28].responsibility'),
      type: t('career.marketing'),
      location: t('position[28].location'),
      time: t('position[28].time'),
      skill: t('position[28].skill'),
    },
    {
      id: 'rd-engineering-specialist',
      title: t('position[29].title'),
      qualification: tm('position[29].qualification'),
      responsibility: tm('position[29].responsibility'),
      type: t('career.electronics'),
      location: t('position[29].location'),
      time: t('position[29].time'),
      skill: t('position[29].skill'),
    },
    {
      id: 'connector-engineer',
      title: t('position[30].title'),
      qualification: tm('position[30].qualification'),
      responsibility: tm('position[30].responsibility'),
      type: t('career.electronics'),
      location: t('position[30].location'),
      time: t('position[30].time'),
      skill: t('position[30].skill'),
    },
    {
      id: 'admin-secretary',
      title: t('position[31].title'),
      qualification: tm('position[31].qualification'),
      responsibility: tm('position[31].responsibility'),
      type: t('career.business'),
      location: t('position[31].location'),
      time: t('position[31].time'),
      skill: t('position[31].skill'),
    },
    {
      id: 'business-development-manager',
      title: t('position[32].title'),
      qualification: tm('position[32].qualification'),
      responsibility: tm('position[32].responsibility'),
      competitive: tm('position[32].competitive'),
      type: t('career.business'),
      location: t('position[32].location'),
      time: t('position[32].time'),
      skill: t('position[32].skill'),
    },
    {
      id: 'junior-business-development-manager',
      title: t('position[33].title'),
      qualification: tm('position[33].qualification'),
      responsibility: tm('position[33].responsibility'),
      competitive: tm('position[33].competitive'),
      type: t('career.business'),
      location: t('position[33].location'),
      time: t('position[33].time'),
      skill: t('position[33].skill'),
    },
  ]

  const selectedPosition = [
    {
      value: t('career.category.all'),
    },
    {
      value: t('career.assistant'),
    },
    {
      value: t('career.programmer'),
    },
    {
      value: t('career.accounting'),
    },
    {
      value: t('career.business'),
    },
    {
      value: t('career.sales'),
    },
    {
      value: t('career.marketing'),
    },
    {
      value: t('career.engineer'),
    },
    {
      value: t('career.electronics'),
    },
  ]

  const selectLocation = [
    {
      value: t('career.location.th'),
    },
    {
      value: t('career.location.nl'),
    },
  ]

  return { jobPosition, selectedPosition, selectLocation }
}
